# Generated by Django 3.0.5 on 2020-04-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_image',
            new_name='book_image',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='user_id_supplier',
            new_name='user_id',
        ),
    ]
