# Generated by Django 3.0.2 on 2020-04-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=15)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('user_image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('landmark', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('zip_code', models.CharField(max_length=6)),
                ('status', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=100)),
                ('time_zone', models.CharField(default='', max_length=100)),
                ('user_lat', models.FloatField()),
                ('user_lng', models.FloatField()),
            ],
            options={
                'db_table': 'USER',
            },
        ),
    ]
